# {{.ProjectName}}

{{.ProjectName}} is a Go backend skeleton generated by `ddd-bootstrap`.

Stack:

- Go
- Fiber v3
- Uber Fx
- GORM Gen
- PostgreSQL

Key directories:

- `app/ohs`: protocol boundary, DTOs, commands, queries, and appservice use cases.
- `app/domain`: domain entities and domain services.
- `app/acl`: ports, mappers, and adapters for persistence or external systems.
- `app/infra`: system errors, constants, validation, messaging, jobs, and runtime concerns.
- `configs`: application configuration loading and YAML files.
- `cmd/server/di`: Fx composition root.
- `cmd/gorm-gen`: GORM Gen entry and query interfaces.
- `sql`: schema and table DDL.

The generated `health` module is only an initialization check. Do not treat it as business code.

This architecture has no standalone `app/application` layer. Application services live under `app/ohs/local/appservice`.

Before editing generated projects, read `AGENTS.md`, `.agent/rules/*.md`, and the nearest `.agent.md`.

Validate architecture drift with:

```bash
ddd-bootstrap validate --project-root .
```

Generate or refresh GORM Gen DAO/model files with:

```bash
go run ./cmd/gorm-gen
```

Do not hand-write or patch generated DAO/model `.gen.go` files. If they are
missing, run `go run ./cmd/gorm-gen`.

If the environment cannot access the Go proxy or private modules, initialize
with `--skip-go-mod-tidy` and run `go mod download` / `go mod tidy` later in an
environment with dependency access.
